### PR TITLE
get stats from data

### PR DESCRIPTION
**Pull request by aaronhans**
Get the stats data from the file the API is writing instead of the WP table-data

### CODE REVIEW

**Comment by carterm** [comment]
So are we done using the Wordpress table for this then?

**Comment by aaronhans** [comment]
That is the plan. I need to make sure I understood the snowflake table structure properly. The first location I used to get this data went away. I think I am using a stable set of tables now.

I added tasks to cleanup the unused files to https://github.com/cagov/covid19/issues/556

**Comment by abquirarte** [comment]
So is this operational now? Want to make sure we are cross-validating with
what CDT has on the update page just in case this goes through other data
curation that we are not aware of.

<https://twitter.com/cadotgov>

**Comment by aaronhans** [comment]
This is operational now. Karim is no longer making manual updates to the stats data. @abquirarte Is there a dba or someone who can advise me on the best place to be retrieving different pieces of information? I have manual and programmatic SQL access but some of the tables are fluid.

**Pull request merged**
