### PR TITLE
CCG-1136

### PR DESCRIPTION
**Pull request by m-sullivan7**
I'm attempting to add an arrow button link to the bottom of the page that directs to the equity page. Let's definitely stage this to see if I did it right. :D

### CODE REVIEW

**Comment by carterm** [comment]
headed to staging...

**Comment by m-sullivan7** [comment]
Once more to staging if that's OK. I think I was just one `</div>` away from hitting it on the nose!

**Comment by aaronhans** [comment]
Looks like Konstantin is fixing this, expect a PR from him to make sure this still works even with the tableau above overflowing. Thanks @kkoryaka!

**Comment by aaronhans** [comment]
Konstantin please close if you have a full PR with these changes or add to this one if it is still useful

**Comment by m-sullivan7** [comment]
Konstantin and I have tested in staging and everything is working great. This is ready to be merged to production. I would do it, but as the ticket creator I can't. ;)

**Review by chachasikes — APPROVED** [review]
Looks good - I see the link on the State Dashboard page.

**Pull request merged**
