### PR TITLE
Working redirect code

### PR DESCRIPTION
**Pull request by carterm**
shows how to capture the redirect data from the wordpress table.

This code reads the `page-redirect-table` in covid and creates a table that can update s3.  This will account for 301 and 410.  This uses the same method cannabis is using.  There is a code sample to update the bucket wide redirect config If manual wild card redirect systems for translations etc need to be manually added.

### CODE REVIEW

**Comment by aaronhans** [comment]
Excellent, thanks Carter!

**Comment by carterm** [comment]
I have not tested it live, but there is a debug launch in the project to test the creation of the dataset to upload to S3.

**Comment by carterm** [comment]
The code works, but it has not been added to the deployment script.

**Comment by aaronhans** [comment]
I added integration into production build workflow

Also removed old Azure preproduction workflow because that migration to AWS is complete

**Review by aaronhans — APPROVED** [review]

**Review by jbum — APPROVED** [review]
Thanks Aaron!

**Pull request merged**
