### PR TITLE
Minimum Effort!

### PR DESCRIPTION
**Pull request by xjensen**
Hey Alpha, 

As promised, here are a couple minor contributions. 

* Remember the problems we saw with special characters earlier today? I fixed up a few more occurrences within HTML page titles and meta descriptions.

* I added an 11ty filter to help format dates and times within templates. Please note that you'll need to `npm install` to pull in an extra dependency to make this work. You could use it like so.

``` html
<p>Page updated on <time>{{ publishdate | formatDate }}</time>.</p>
```

I also added an *Updated* date to the `page.njk` template. Not sure if you want this; it may be inaccurate or unwanted at this time.

### CODE REVIEW

**Comment by aaronhans** [comment]
Thanks @xjensen! Appreciate your help.

@artuoma please let us know if you approve adding publish dates to pages

**Comment by carterm** [comment]
Index.html and translate.html need GMT dates for this to work.

**Comment by carterm** [comment]
Fixed conflicts.

**Comment by carterm** [comment]
We'll give it a shot

**Pull request merged**
