### PR TITLE
Removing "Unknown" filter from Vaccine Age data

### PR DESCRIPTION
**Pull request by carterm**
Displays "Unknown" on the vaccine age data.

Refer to JIRA...
https://digital-ca-gov.atlassian.net/browse/CCG-1982

### CODE REVIEW

**Comment by carterm** [comment]
> Approved (technically) - but setting as a comment: what's the nature of this change?

There was interest in showing the unknown data.  Not sure if it's going to happen or not, but if so we have the PR.

**Comment by abquirarte** [comment]
what is this?

Angelica Quirarte, "Angie"
Deputy Director | Office of Digital Innovation
c: 916-526-5510 or 916-812-6864
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by aaronhans** [comment]
https://digital-ca-gov.atlassian.net/browse/CCG-1982

**Review by kkoryaka — APPROVED** [review]
No more unknown stuff

**Comment by jbum** [comment]
I'm going to close this old Pull Request, as Michael Marks has suggested that we continue to omit this category from the chart.

**Pull request closed without merging**
