### PR TITLE
Replacing Footer data

### PR DESCRIPTION
**Pull request by carterm**
Removing the use of the "Footer Data" Wordpress files and using the translated "common-page-labels" going forward.  This PR includes a starting version of the translated structures, but we should wait for Avantpage to finish translations before publishing.

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
cool

**Comment by carterm** [comment]
still waiting to make sure the common page labels data is translated correctly.

**Comment by carterm** [comment]
Translations came in ok.  Might be ready for this one.

**Comment by carterm** [comment]
Make sure json updates are working...
https://github.com/cagov/covid19/pull/1972

**Comment by carterm** [comment]
Confirmed new translations work

**Pull request merged**
