### PR TITLE
Update equity page content

### PR DESCRIPTION
**Pull request by chachasikes**

### CODE REVIEW

**Comment by chachasikes** [comment]
Sync Wordpress changes - Please review that this had all your changes @jbum 
@aaronhans may also be editing this same file

**Review by jbum — APPROVED** [review]
Looks different but harmless.

**Comment by jbum** [comment]
The learn more section has been replaced with some explicit markup that I think was being generated in js (I forget why). Will clean up the js side if needed after this merge.

**Comment by chachasikes** [comment]
I think Aaron got this already with other updates, so gonna close it to be safe. @aaronhans

**Pull request closed without merging**
