### PR TITLE
Popular Search list and multi-lang support

### PR DESCRIPTION
**Pull request by carterm**
added Popular Queries and Multi-language support for the search.

Will require this draft to be published...
https://as-go-covid19-d-001.azurewebsites.net/wp-admin/post.php?post=4164&action=edit

### CODE REVIEW

**Comment by aaronhans** [comment]
I saw we got some feedback from Peggy on this feature. Did we get signoff from Art, Angie too?

**Comment by carterm** [comment]
Publish this WP draft when this is merged...
https://as-go-covid19-d-001.azurewebsites.net/wp-admin/post.php?post=4164&action=edit

**Comment by carterm** [comment]
> I saw we got some feedback from Peggy on this feature. Did we get signoff from Art, Angie too?

We'll need Angie to approve this before we go.

**Comment by abquirarte** [comment]
@carterm 👀 reviewed. And I like it! I also saw that Art reviewed. Go forth and merge! 
image

**Comment by carterm** [comment]
Some IE11 issues to resolve with search before moving forward.

**Pull request merged**
