### PR TITLE
Ccg 750 move pagenames to translatable wordpress data

### PR DESCRIPTION
**Pull request by carterm**
- Moved all the menu information to a translatable WP file. - https://as-go-covid19-d-001.azurewebsites.net/wp-admin/post.php?post=7484
- removed the old structure.
- made sandbox code more generic

Solution for...
https://digital-ca-gov.atlassian.net/browse/CCG-750

### CODE REVIEW

**Review by chachasikes — APPROVED** [review]
Mice - lots of menu changes for translations.
What does sandbox misc refer to?

**Comment by aaronhans** [comment]
Pretty nice Carter! Would you please explain how to use the sandbox and launch.json stuff?

**Review by aaronhans — APPROVED** [review]

**Comment by carterm** [comment]
> Pretty nice Carter! Would you please explain how to use the sandbox and launch.json stuff?

Screen Shot 2020-12-07 at 12 34 26 PM

**Comment by carterm** [comment]
I'll add a readme to the folder.

**Review by jbum — APPROVED** [review]
Looking good!

**Pull request merged**
