### PR TITLE
Translated home pages

### PR DESCRIPTION
**Pull request by carterm**
Provides translations for the homepage, and localizes dates.

Remove Stat WP files when deploying.

### CODE REVIEW

**Comment by carterm** [comment]
Before...Screen Shot 2020-08-04 at 1 59 45 PM

**Comment by abquirarte** [comment]
Amazing!! 🎉

**Comment by carterm** [comment]
After Screen Shot 2020-08-04 at 1 59 57 PM

**Comment by carterm** [comment]
Dates Before
Screen Shot 2020-08-04 at 2 15 47 PM

**Comment by carterm** [comment]
Dates After
Screen Shot 2020-08-04 at 2 15 51 PM

**Comment by carterm** [comment]
Dates After
Screen Shot 2020-08-04 at 2 15 51 PM

**Comment by abquirarte** [comment]
👍

**Pull request merged**
