### PR TITLE
Homepage translation link/text integration fixes

### PR DESCRIPTION
**Pull request by carterm**
Fixing the translation integration for “Recent Updates” and “For businesses”

For https://digital-ca-gov.atlassian.net/browse/CCG-2085

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
thanks Carter

**Review by chachasikes — COMMENTED** [review]
Fun fact: to test branches with quotes - prefix with the escape character  eg. \"
cc @carterm

**Comment by chachasikes** [comment]
Is this supposed to load the titles? @carterm, if so I don't see them

**Comment by carterm** [comment]
Titles are English placeholders for now, they will be translated by Avantpage later.

**Pull request merged**
