### PR TITLE
Rebuilding the build system

### PR DESCRIPTION
**Pull request by xjensen**
The build system gave me a lot of trouble on Windows. So I rebuilt it. It's working consistently across both Mac and Windows. Here are my testing platforms at the moment.

* Windows 10 with Node 12.18.3.
* MacOS 10.15 (Catalina) with Node 14.7.0.

**Much has changed.** Here's a list of the highlights.

* Webpack configs have been removed.
* Additional Rollup configs have been added.
     * The es5.js file is now generated through Rollup instead of Webpack. See *src/js/rollup.config.es5.js*.
     * There's a new Rollup config that bundles together all other Rollup configs, so they can all be called at once. It's faster. See *src/js/rollup.config.all.js*.
* Gulp has been added to help manage build steps. See *gulpfile.js*.
* CSS builds are now handled through Gulp instead of Webpack.
* CSS minifying is now handled during the build process, rather than through Eleventy's template filters. Related Eleventy code has been removed from *.eleventy.js*.
* Separate watchers for webpack/rollup/eleventy have been replaced with Gulp-based watchers and a custom implementation of Browsersync. 
* There's a new "development mode" for rapidly prototyping CSS changes. The goal is to enable rapid iteration on CSS without requiring costly Eleventy and PurgeCSS rebuilds for every change.
     * There's a new *pages/_data/env.js* file which exposes environment data to Eleventy templates.
     * Note small but meaningful changes to how CSS is included in *pages/_includes/main.njk* and *page.njk*.
     * In this mode, CSS is not purged and embedded into the HTML. Instead, a full, un-purged CSS file is used across the site. 
* Npm scripts have been modified to accommodate these changes. 
     * `npm run build` builds everything.
     * `npm run build:css`, `npm run build:js`, and `npm run build:site` perform respective functions.
     * `npm run clean` will wipe out the *docs* folder if you want a fresh start.
     * `npm run deploy` will do a `clean` prior to a `build`.
     * `npm run local` will build and serve the site for live local development.
     * `npm run local:dev` will enable the *development mode* of `local`, see above.

Further information about rationale for these changes can be found in #801.

Changes here are pretty extensive, so I'd say plenty of tire kicking is in order before proceeding with the merge.

### CODE REVIEW

**Comment by xjensen** [comment]
Here's a list of outstanding questions.  

* The current Webpack-based CSS builds create some files (in the *dist* folder, if memory serves), but I'm not sure if they're needed. Everything seemed to be covered already by Eleventy's Passthrough Copy. There are some other hash-named JS files going to *docs/js* which do not seem necessary. Still, I'm not sure if a downstream build system needs this output, etc. It would be good to get a second opinion.
* I've tested the new legacy ES5 Javascript in IE11. It seems to be working as well as the old configuration, at least. If there are any other key browsers among our users we need to check, I'll be happy to take a look.
* It now occurs to me that the new CSS development mode could easily be extended to Javascript embeds as well. We can quickly add those changes if desired. Or remove development mode altogether.

**Comment by xjensen** [comment]
I just realized I still need to extract static assets from imported web components. I'll do that next.

**Comment by carterm** [comment]
Oh wow this is great!  I was able to run it locally.

**Comment by aaronhans** [comment]
This is incredible work @xjensen amazed you have been able to fit all this progress into nights and weekends. Thank you for all these improvements.

**Comment by xjensen** [comment]
Thanks!

I've chunked out some of these changes into smaller PRs: #1284, #1285, and #1286. These new PRs do not cover everything here. They're a second step following the work by @carterm earlier today on #1276 and #1283.

**Comment by aaronhans** [comment]
Having a separate dev config where the css isn't inlined is a big improvement. I wonder how costly the purge step is because I  am a little nervous about people getting used to working in dev mode and pushing updates without verifying everything is cool after the purge is applied (This is probably a bug that needs to be caught visually)

**Comment by xjensen** [comment]
In my testing so far, the CSS purging in this new Gulp-based build system takes two or three seconds. (That's two or three seconds to purge the home.css and built.css files in parallel.) It's slower than instant, but still not bad. We could definitely give it a shot.

**Pull request merged**
