### PR TITLE
Ccg 1384/kk blueprint a11y

### PR DESCRIPTION
**Pull request by kkoryaka**
Moving this to prod

### CODE REVIEW

**Review by chachasikes — COMMENTED** [review]
Awesome! 
I will also port this into the work I'm doing for some redesigned features for the roadmap page.

I see this is pushed to master, not preproduction.

**Comment by kkoryaka** [comment]
@chachasikes

> Awesome!
> I will also port this into the work I'm doing for some redesigned features for the roadmap page.
> 
> I see this is pushed to master, not preproduction.

This is already in reproduction. I am moving it to master now.

**Review by aaronhans — APPROVED** [review]
thanks Konstantin!

**Review by jbum — APPROVED** [review]
On a scale of 1 to 10, I give it an 11.

**Pull request merged**
