### PR TITLE
Translation - schools-may-reopen-in-these-counties

### PR DESCRIPTION
**Pull request by jorgv**

### CODE REVIEW

**Review by chachasikes — APPROVED** [review]
Looks clean

**Review by chachasikes — CHANGES_REQUESTED** [review]
wait... the date format changed this might be bad.

**Review by chachasikes — APPROVED** [review]
Ran this & checked safer economy & state dashboard - these variables are display only & not used for calculations.

**Comment by chachasikes** [comment]
@jbum this looks fine - but the tier data is also used in state dashboard - looks like it's used same way was for safer economy & page rendered fine - but adding you - we run these other dates through formateDate2 function

**Review by aaronhans — APPROVED** [review]

**Pull request merged**
